server:
  port: 8081
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.120.20:3306/vueadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    host: 192.168.120.20
    port: 6379

  security:
    user:
      name: admin
      password: admin
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

shf:
  jwt:
    header: Authorization
    expire: 604800 #7天，秒单位
    secret: ji8n3439n439n43ld9ne9343fdfer49h

logging:
  level:
    com.shf: debug
